#+TITLE: Reproducing Analysis of {{{tool}}}
#+AUTHOR: Karl Gemayel
#+Date: May 21 2020 
#+OPTIONS: toc:2 H:3 num:3

#+LATEX_HEADER_EXTRA:  \usepackage{mdframed}
#+LATEX_HEADER_EXTRA: \BeforeBeginEnvironment{minted}{\begin{mdframed}}
#+LATEX_HEADER_EXTRA: \AfterEndEnvironment{minted}{\end{mdframed}}
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}

#+MACRO: tool MetaGeneMark2

# #+SUBTITLE: The commands used to set up, reproduce, and graph results from the {{{tool}}} paper


* Introduction
This document serves as a step-by-step instruction manual on how to replicate results from the {{{tool}}} paper. 

* Downloading and installing
** Code
Downloading the code is fairly straightforward using =git=. The latest version can be downloaded from =WEBSITE=. To install, simply run 
#+begin_src bash
source config.sh
source install.sh
#+end_src

The first command loads all environment variables (including paths to data directories, binaries, etc...), and the second command creates an executable from all python files and stores them in =$bin= for easy access. For non-unix users, you can find the python driver files in =$driverpython=.
** External Tools
   {{{tool}}} and {{{tool}}}+ and their analysis rely on a handful of external tools. The following need to be installed:
   - GeneMarkS-2
     - Used for building {{{tool}}}+ predictions, and for analysis
     - Link: http://exon.gatech.edu/GeneMark/license_download.cgi
   - ClustalO:
     - Used for constructing multiple sequence alignments
     - Link: http://www.clustal.org/omega/#Download
   - Prodigal:
     - Used for initial analysis of gene-start prediction status
     - Link: https://github.com/hyattpd/Prodigal

** Data
   TODO

   
* Code and data structure

After installing {{{tool}}}, you will have the following structure:

#+begin_src dot :file dir.pdf :cmdline -Tpdf
  digraph{
    sbsp -> data;
    sbsp -> runs;
    sbsp -> lists;
    sbsp -> code;
    sbsp -> bin

    code -> python;
    code -> bash;


    data -> G1;
    data -> G2;
    data -> "...";
    data -> GN;

    G1 -> "sequence.fasta";
    G1 -> "ncbi.gff";
    G1 -> "verified.gff";

    python -> lib;
    python -> driver;
    }
#+end_src

#+RESULTS:
[[file:dir.pdf]]


The =bin= directory contains all executables related to {{{tool}}}, while the =bin_external= may contain external tools, such as GeneMarkS-2 or Prodigal. 

The =data= directory will contain raw genome files (sequence and annotation labels) downloaded from NCBI. In particular, upon initial download of the code, it should contain the genomic sequences for the genomes with experimentally verified gene-starts.

The =list= directory has files that contain different lists of genomes (for example, those with verified genes, those selected as NCBI query genomes, etc...)

Finally the =runs= directory will contain runs of different tools, such as {{{tool}}}, GeneMarkS-2, or Prodigal (as well as one for NCBI's =PGAP=). These will be placed in a subdirectory per genome, as shown below.

#+begin_src dot :file dir_runs.pdf :cmdline -Tpdf
  digraph {
    gms21 [label="gms2"]
    sbsp1 [label="mgm2"]
    prodigal1 [label="prodigal"]

    gms22 [label="gms2"]
    sbsp2 [label="mgm2"]
    prodigal2 [label="prodigal"]

  
  runs -> G1;
    runs -> G2;
    runs -> "...";
    runs -> GN;

    G1 -> gms21;
    G1 -> sbsp1;
    G1 -> prodigal1;
    G2 -> gms22;
    G2 -> sbsp2;
    G2 -> prodigal2;

  }
#+end_src

#+RESULTS:
[[file:dir_runs.pdf]]

* Setting up
** *Important*: Python environment
   Scripts to build and analyze results rely on a handful of python packages. The recommended way to install them is to use the =conda= package manager, and simply run 
   #+begin_src bash
     conda env create -f install/conda_mgm2.yaml
   #+end_src 

   
   To activate this python environment, run 
   #+begin_src bash
     conda activate mg-starts
   #+end_src 
   This automatically loads the correct python libraries and executables into =$PATH=.



* Experiments
** Building MGM2 start models
   #+begin_src bash
     $bin/build_mgm_models_from_gms2_models_py.sh --
   #+end_src
** Run Tools on verified set
   #+begin_src bash
     for tool in gms2 prodigal mprodigal mgm2 mgm; do
       $bin/run_tool_on_genome_list_py.sh --pf-gil $lists/verified.list --type auto --tool $tool --pf-mgm-mod $base/bin_external/gms2/mgm_11.mod --pf-mgm2-mod $base/bin_external/mgm2/mgm2_11.mod
     done
   #+end_src


